package ru.example.news.aop;

public enum ValidationType {
    USER_DELETE, USER_UPDATE, USER_FIND_BY_ID,
    NEWS_UPDATE, NEWS_DELETE,
    COMMENTS_UPDATE, COMMENTS_DELETE,
    TOPIC_SAVE, TOPIC_UPDATE, TOPIC_DELETE
}
