spring:
  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/books_db
    username: postgres
    password: postgres
    hikari:
      schema: books_schema
      connection-timeout: 10000

app:
  upload:
    enable: true
    dataPath: src/main/resources/data/books-mock-data.json
    defaultBooksNumber: 20
  cache:
    enable: true
    cacheType: redis
    cacheNames:
      - dbBooks
      - dbBooksByCategory
      - dbBookByNameAndAuthor
      - dbBookById
      - dbBookByName
      - dbBooksByAuthor
    properties:
      dbBooks:
        expiry: 3m
      dbBooksByCategory:
        expiry: 3m
      dbBookByNameAndAuthor:
        expiry: 3m
      dbBookById:
        expiry: 3m
      dbBookByName:
        expiry: 3m
      dbBooksByAuthor:
        expiry: 3m

